import Link from "next/link";
import "./globals.css";
import Image from "next/image";
import { Menu } from "lucide-react";

export const metadata = {
  title: "Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-[1024px] mx-auto px-4">
        <nav className="p-8 border border-gray-800 bg-gray-900 rounded-2xl mt-6 shadow-2xl flex gap-12 justify-between">
          <Link className="flex gap-6" href={"/"}>
            <Image
              alt="Brand Image"
              width={0}
              height={0}
              src={"/vercel.svg"}
              className="w-[30px] h-auto"
            />
            <span className="text-2xl text-white font-semibold">
              NextJS App
            </span>
          </Link>

          <div className="flex gap-4 items-center flex-1">
            <Link href={"/products"}>
              <span className="text-lg text-gray-300 hover:text-white hover:bg-gray-800 transition px-4 py-2 rounded-md">
                Products
              </span>
            </Link>
            <Link href={"/todos"}>
              <span className="text-lg text-gray-300 hover:text-white hover:bg-gray-800 transition px-4 py-2 rounded-md">
                Todos
              </span>
            </Link>
          </div>

          <Menu className="text-gray-600 hover:text-white transition cursor-pointer" />
        </nav>
        {children}
      </body>
    </html>
  );
}
